export const years: string[] = [
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
];

export const raceTypes: string[] = ["Race", "Qualifying", "FP3", "FP2", "FP1"];

type Session = Record<string, string[]>;

export const sessions: Session = {
  "2025": [
    "Australian Grand Prix",
    "Chinese Grand Prix",
    "Japanese Grand Prix",
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Miami Grand Prix",
    "Emilia Romagna Grand Prix",
    "Monaco Grand Prix",
    "Spanish Grand Prix",
    "Canadian Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Belgian Grand Prix",
    "Hungarian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Azerbaijan Grand Prix",
    "Singapore Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Las Vegas Grand Prix",
    "Qatar Grand Prix",
    "Abu Dhabi Grand Prix",
  ],
  "2024": [
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Australian Grand Prix",
    "Japanese Grand Prix",
    "Chinese Grand Prix",
    "Miami Grand Prix",
    "Emilia Romagna Grand Prix",
    "Monaco Grand Prix",
    "Canadian Grand Prix",
    "Spanish Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Azerbaijan Grand Prix",
    "Singapore Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Las Vegas Grand Prix",
    "Qatar Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2023": [
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Australian Grand Prix",
    "Azerbaijan Grand Prix",
    "Miami Grand Prix",
    "Monaco Grand Prix",
    "Spanish Grand Prix",
    "Canadian Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Japanese Grand Prix",
    "Qatar Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Las Vegas Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2022": [
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Australian Grand Prix",
    "Emilia Romagna Grand Prix",
    "Miami Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Azerbaijan Grand Prix",
    "Canadian Grand Prix",
    "British Grand Prix",
    "Austrian Grand Prix",
    "French Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Japanese Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2021": [
    "Bahrain Grand Prix",
    "Emilia Romagna Grand Prix",
    "Portuguese Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Azerbaijan Grand Prix",
    "French Grand Prix",
    "Styrian Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Russian Grand Prix",
    "Turkish Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Qatar Grand Prix",
    "Saudi Arabian Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2020": [
    "Austrian Grand Prix",
    "Styrian Grand Prix",
    "Hungarian Grand Prix",
    "British Grand Prix",
    "70th Anniversary Grand Prix",
    "Spanish Grand Prix",
    "Belgian Grand Prix",
    "Italian Grand Prix",
    "Tuscan Grand Prix",
    "Russian Grand Prix",
    "Eifel Grand Prix",
    "Portuguese Grand Prix",
    "Emilia Romagna Grand Prix",
    "Turkish Grand Prix",
    "Bahrain Grand Prix",
    "Sakhir Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2019": [
    "Australian Grand Prix",
    "Bahrain Grand Prix",
    "Chinese Grand Prix",
    "Azerbaijan Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Canadian Grand Prix",
    "French Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "German Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Russian Grand Prix",
    "Japanese Grand Prix",
    "Mexican Grand Prix",
    "United States Grand Prix",
    "Brazilian Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2018": [
    "Australian Grand Prix",
    "Bahrain Grand Prix",
    "Chinese Grand Prix",
    "Azerbaijan Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Canadian Grand Prix",
    "French Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "German Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Russian Grand Prix",
    "Japanese Grand Prix",
    "United States Grand Prix",
    "Mexican Grand Prix",
    "Brazilian Grand Prix",
    "Abu Dhabi Grand Prix"
  ]
};

type Driver = Record<string, string[]>;

export const drivers: Driver = {
  "2025": [
    "Max Verstappen",
    "Yuki Tsunoda",
    "Lando Norris",
    "Oscar Piastri",
    "George Russell",
    "Kimi Antonelli",
    "Liam Lawson",
    "Isack Hadjar",
    "Charles Leclerc",
    "Lewis Hamilton",
    "Fernando Alonso",
    "Lance Stroll",
    "Pierre Gasly",
    "Jack Doohan",
    "Franco Colapinto",
    "Alexander Albon",
    "Carlos Sainz Jr",
    "Oliver Bearman",
    "Esteban Ocon",
    "Nico Hülkenberg",
    "Gabriel Bortoleto"
  ],
  "2024": [
    "Lewis Hamilton",
    "George Russell",
    "Max Verstappen",
    "Sergio Pérez",
    "Charles Leclerc",
    "Carlos Sainz Jr",
    "Oliver Bearman",
    "Lando Norris",
    "Oscar Piastri",
    "Liam Lawson",
    "Daniel Ricciardo",
    "Fernando Alonso",
    "Lance Stroll",
    "Esteban Ocon",
    "Pierre Gasly",
    "Jack Doohan",
    "Yuki Tsunoda",
    "Logan Sargeant",
    "Alexander Albon",
    "Franco Colapinto",
    "Guanyu Zhou",
    "Valtteri Bottas",
    "Kevin Magnussen",
    "Nico Hülkenberg"
  ],
  "2023": [
    "Lewis Hamilton",
    "George Russell",
    "Max Verstappen",
    "Sergio Pérez",
    "Charles Leclerc",
    "Carlos Sainz Jr",
    "Lando Norris",
    "Oscar Piastri",
    "Nyck de Vries",
    "Liam Lawson",
    "Daniel Ricciardo",
    "Fernando Alonso",
    "Lance Stroll",
    "Esteban Ocon",
    "Pierre Gasly",
    "Yuki Tsunoda",
    "Logan Sargeant",
    "Alexander Albon",
    "Guanyu Zhou",
    "Valtteri Bottas",
    "Kevin Magnussen",
    "Nico Hülkenberg"
  ],
  "2022": [
    "Lewis Hamilton",
    "George Russell",
    "Max Verstappen",
    "Sergio Pérez",
    "Charles Leclerc",
    "Carlos Sainz Jr",
    "Lando Norris",
    "Daniel Ricciardo",
    "Fernando Alonso",
    "Esteban Ocon",
    "Pierre Gasly",
    "Yuki Tsunoda",
    "Sebastian Vettel",
    "Lance Stroll",
    "Nico Hülkenberg",
    "Nicholas Latifi",
    "Alexander Albon",
    "Nyck de Vries",
    "Guanyu Zhou",
    "Valtteri Bottas",
    "Kevin Magnussen",
    "Mick Schumacher"
  ],
  "2021": [
    "Lewis Hamilton",
    "Valtteri Bottas",
    "Max Verstappen",
    "Sergio Pérez",
    "Charles Leclerc",
    "Carlos Sainz Jr",
    "Lando Norris",
    "Daniel Ricciardo",
    "Fernando Alonso",
    "Esteban Ocon",
    "Pierre Gasly",
    "Yuki Tsunoda",
    "Sebastian Vettel",
    "Lance Stroll",
    "George Russell",
    "Nicholas Latifi",
    "Kimi Räikkönen",
    "Antonio Giovinazzi",
    "Robert Kubica",
    "Mick Schumacher",
    "Nikita Mazepin"
  ],
  "2020": [
    "Lewis Hamilton",
    "Valtteri Bottas",
    "Sebastian Vettel",
    "Charles Leclerc",
    "Max Verstappen",
    "Alexander Albon",
    "Lando Norris",
    "Carlos Sainz Jr",
    "Daniel Ricciardo",
    "Esteban Ocon",
    "Pierre Gasly",
    "Sergio Pérez",
    "Romain Grosjean",
    "Kevin Magnussen",
    "Pietro Fittipaldi",
    "Lance Stroll",
    "Nico Hülkenberg",
    "George Russell",
    "Nicholas Latifi",
    "Kimi Räikkönen",
    "Antonio Giovinazzi",
    "Daniil Kvyat",
    "Jack Aitken"
  ],
  "2019": [
    "Lewis Hamilton",
    "Valtteri Bottas",
    "Sebastian Vettel",
    "Charles Leclerc",
    "Max Verstappen",
    "Pierre Gasly",
    "Daniel Ricciardo",
    "Nico Hülkenberg",
    "Romain Grosjean",
    "Kevin Magnussen",
    "Carlos Sainz Jr",
    "Lando Norris",
    "Sergio Pérez",
    "Lance Stroll",
    "Kimi Räikkönen",
    "Antonio Giovinazzi",
    "Daniil Kvyat",
    "Alexander Albon",
    "George Russell",
    "Robert Kubica"
  ],
  "2018": [
    "Lewis Hamilton",
    "Valtteri Bottas",
    "Sebastian Vettel",
    "Kimi Räikkönen",
    "Daniel Ricciardo",
    "Max Verstappen",
    "Nico Hülkenberg",
    "Sergio Pérez",
    "Carlos Sainz Jr",
    "Fernando Alonso",
    "Esteban Ocon",
    "Charles Leclerc",
    "Romain Grosjean",
    "Kevin Magnussen",
    "Pierre Gasly",
    "Stoffel Vandoorne",
    "Marcus Ericsson",
    "Lance Stroll",
    "Brendon Hartley",
    "Sergey Sirotkin"
  ]
};