export const years: string[] = [
  "2025",
  "2024",
  "2023",
  "2022",
  "2021",
  "2020",
  "2019",
  "2018",
];

export const raceTypes: string[] = ["Race", "Qualifying", "FP3", "FP2", "FP1"];

type Session = Record<string, string[]>;

export const sessions: Session = {
  "2025": [
    "Australian Grand Prix",
    "Chinese Grand Prix",
    "Japanese Grand Prix",
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Miami Grand Prix",
    "Emilia Romagna Grand Prix",
    "Monaco Grand Prix",
    "Spanish Grand Prix",
    "Canadian Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Belgian Grand Prix",
    "Hungarian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Azerbaijan Grand Prix",
    "Singapore Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Las Vegas Grand Prix",
    "Qatar Grand Prix",
    "Abu Dhabi Grand Prix",
  ],
  "2024": [
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Australian Grand Prix",
    "Japanese Grand Prix",
    "Chinese Grand Prix",
    "Miami Grand Prix",
    "Emilia Romagna Grand Prix",
    "Monaco Grand Prix",
    "Canadian Grand Prix",
    "Spanish Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Azerbaijan Grand Prix",
    "Singapore Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Las Vegas Grand Prix",
    "Qatar Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2023": [
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Australian Grand Prix",
    "Azerbaijan Grand Prix",
    "Miami Grand Prix",
    "Monaco Grand Prix",
    "Spanish Grand Prix",
    "Canadian Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Japanese Grand Prix",
    "Qatar Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Las Vegas Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2022": [
    "Bahrain Grand Prix",
    "Saudi Arabian Grand Prix",
    "Australian Grand Prix",
    "Emilia Romagna Grand Prix",
    "Miami Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Azerbaijan Grand Prix",
    "Canadian Grand Prix",
    "British Grand Prix",
    "Austrian Grand Prix",
    "French Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Japanese Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2021": [
    "Bahrain Grand Prix",
    "Emilia Romagna Grand Prix",
    "Portuguese Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Azerbaijan Grand Prix",
    "French Grand Prix",
    "Styrian Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Dutch Grand Prix",
    "Italian Grand Prix",
    "Russian Grand Prix",
    "Turkish Grand Prix",
    "United States Grand Prix",
    "Mexico City Grand Prix",
    "São Paulo Grand Prix",
    "Qatar Grand Prix",
    "Saudi Arabian Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2020": [
    "Austrian Grand Prix",
    "Styrian Grand Prix",
    "Hungarian Grand Prix",
    "British Grand Prix",
    "70th Anniversary Grand Prix",
    "Spanish Grand Prix",
    "Belgian Grand Prix",
    "Italian Grand Prix",
    "Tuscan Grand Prix",
    "Russian Grand Prix",
    "Eifel Grand Prix",
    "Portuguese Grand Prix",
    "Emilia Romagna Grand Prix",
    "Turkish Grand Prix",
    "Bahrain Grand Prix",
    "Sakhir Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2019": [
    "Australian Grand Prix",
    "Bahrain Grand Prix",
    "Chinese Grand Prix",
    "Azerbaijan Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Canadian Grand Prix",
    "French Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "German Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Russian Grand Prix",
    "Japanese Grand Prix",
    "Mexican Grand Prix",
    "United States Grand Prix",
    "Brazilian Grand Prix",
    "Abu Dhabi Grand Prix"
  ],
  "2018": [
    "Australian Grand Prix",
    "Bahrain Grand Prix",
    "Chinese Grand Prix",
    "Azerbaijan Grand Prix",
    "Spanish Grand Prix",
    "Monaco Grand Prix",
    "Canadian Grand Prix",
    "French Grand Prix",
    "Austrian Grand Prix",
    "British Grand Prix",
    "German Grand Prix",
    "Hungarian Grand Prix",
    "Belgian Grand Prix",
    "Italian Grand Prix",
    "Singapore Grand Prix",
    "Russian Grand Prix",
    "Japanese Grand Prix",
    "United States Grand Prix",
    "Mexican Grand Prix",
    "Brazilian Grand Prix",
    "Abu Dhabi Grand Prix"
  ]
};
